# Benchmark the reliability solvers on the problems

In this example, we show how to run all the methods on all the problems and get the computed probability.

In [1]:
import openturns as ot
import numpy as np
import otbenchmark as otb
import pandas as pd
import csv
from tqdm import tqdm
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from matplotlib import colors

We import the list of reliability problems.

In [2]:
benchmarkProblemList = otb.ReliabilityBenchmarkProblemList()
numberOfProblems = len(benchmarkProblemList)
numberOfProblems

26

In [3]:
problem = benchmarkProblemList[15]
print(problem.getName())
event = problem.getEvent()
inputVector = event.getAntecedent()
distribution = inputVector.getDistribution()
dimension = distribution.getDimension()
print("Dim = %.d" % dimension)
print("Beta = %.2f" % problem.computeBeta())

RP89
Dim = 2
Beta = 2.55

In [4]:
problem_names = [
    benchmarkProblem.getName() for benchmarkProblem in benchmarkProblemList
]
columns = ["$d$", r"$p_f$", r"$\beta$"]
df_problems_list = pd.DataFrame(index=problem_names, columns=columns,)
for problem in benchmarkProblemList:
    name = problem.getName()
    d = problem.getEvent().getAntecedent().getDistribution().getDimension()
    pf = problem.getProbability()
    beta = problem.computeBeta()
    df_problems_list.loc[name] = [int(d), pf, beta]
pd.set_option("display.float_format", lambda x: "%.3e" % x)
df_problems_list

                           $d$     $p_f$    $\beta$
RP8                          6 7.898e-04  3.160e+00
RP14                         5 7.520e-03  2.431e+00
RP22                         2 4.160e-03  2.639e+00
RP24                         2 2.860e-03  2.763e+00
RP25                         2 6.140e-06  4.373e+00
RP28                         2 1.453e-07  5.129e+00
RP31                         2 1.800e-04  3.568e+00
RP33                         3 2.570e-03  2.798e+00
RP35                         2 3.540e-03  2.693e+00
RP38                         7 8.100e-03  2.404e+00
RP53                         2 3.130e-02  1.862e+00
RP55                         2 5.600e-01 -1.510e-01
RP54                        20 9.980e-04  3.091e+00
RP57                         2 2.840e-02  1.905e+00
RP75                         2 1.070e-02  2.301e+00
RP89                         2 5.430e-03  2.547e+00
RP107                       10 2.920e-07  4.996e+00
RP110                        2 3.190e-05  3.998e+00
RP111                        2 7.650e-07  4.807e+00
RP63                       100 3.790e-04  3.368e+00
RP91                         5 6.970e-04  3.196e+00
RP60                         5 4.560e-02  1.689e+00
RP77                         3 2.870e-07  5.000e+00
Four-branch serial system    2 2.186e-03  2.850e+00
R-S                          2 7.865e-02  1.414e+00
Axial stressed beam          2 2.920e-02  1.893e+00

In [5]:
latex_code = df_problems_list.to_latex()
text_file = open("reliability_problems_list.tex", "w")
text_file.write(latex_code)
text_file.close()

## Multi level columns: methods are level 1, metrics are level 2

For several algorithms and all the reliability problems, we want to estimate the failure probability and compare them.

In [6]:
problem_names = [
    benchmarkProblem.getName() for benchmarkProblem in benchmarkProblemList
]
methods = ["Monte Carlo", "FORM", "SORM", "FORM-IS", "Subset"]
metrics = ["Estimated Pf", "Correct digits", "Nb Simu."]
multi_columns = pd.MultiIndex.from_product(
    [methods, metrics], names=["Methods", "Metrics"]
)
multi_columns = multi_columns.insert(0, ("Exact", "Estimated Pf"))
df_multi = pd.DataFrame(
    np.zeros((len(problem_names), len(methods) * len(metrics) + 1)),
    index=problem_names,
    columns=multi_columns,
)

In [7]:
nearestPointAlgorithm = ot.AbdoRackwitz()
maximumOuterSampling = 10 ** 2
blockSize = 10 ** 2
coefficientOfVariation = 0.0

# TODO Make MC larger and investigate why are they so many zeros
for problem in tqdm(benchmarkProblemList):
    problem_name = problem.getName()
    metaAlgorithm = otb.ReliabilityBenchmarkMetaAlgorithm(problem)
    df_multi.loc[problem_name][("Exact", "Estimated Pf")] = problem.getProbability()
    # FORM
    benchmarkResult = metaAlgorithm.runFORM(nearestPointAlgorithm)
    pf, nb_digits, nb_simu = [
        benchmarkResult.computedProbability,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
    ]
    df_multi.loc[
        problem_name,
        [("FORM", "Estimated Pf"), ("FORM", "Correct digits"), ("FORM", "Nb Simu.")],
    ] = [pf, abs(nb_digits), nb_simu]
    # SORM
    benchmarkResult = metaAlgorithm.runSORM(nearestPointAlgorithm)
    pf, nb_digits, nb_simu = [
        benchmarkResult.computedProbability,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
    ]
    df_multi.loc[
        problem_name,
        [("SORM", "Estimated Pf"), ("SORM", "Correct digits"), ("SORM", "Nb Simu.")],
    ] = [pf, abs(nb_digits), nb_simu]
    # MC
    benchmarkResult = metaAlgorithm.runMonteCarlo(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    pf, nb_digits, nb_simu = [
        benchmarkResult.computedProbability,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
    ]
    df_multi.loc[
        problem_name,
        [
            ("Monte Carlo", "Estimated Pf"),
            ("Monte Carlo", "Correct digits"),
            ("Monte Carlo", "Nb Simu."),
        ],
    ] = [pf, abs(nb_digits), nb_simu]
    # FORM-IS
    benchmarkResult = metaAlgorithm.runFORMImportanceSampling(
        nearestPointAlgorithm,
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    pf, nb_digits, nb_simu = [
        benchmarkResult.computedProbability,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
    ]
    df_multi.loc[
        problem_name,
        [
            ("FORM-IS", "Estimated Pf"),
            ("FORM-IS", "Correct digits"),
            ("FORM-IS", "Nb Simu."),
        ],
    ] = [pf, abs(nb_digits), nb_simu]
    # Subset
    benchmarkResult = metaAlgorithm.runSubsetSampling(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    pf, nb_digits, nb_simu = [
        benchmarkResult.computedProbability,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
    ]
    df_multi.loc[
        problem_name,
        [
            ("Subset", "Estimated Pf"),
            ("Subset", "Correct digits"),
            ("Subset", "Nb Simu."),
        ],
    ] = [pf, abs(nb_digits), nb_simu]
# df_multi

100%|██████████| 26/26 [00:10<00:00,  2.39it/s]

In [8]:
df_multi.style.format(
    "{:.2f}", subset=[(method, "Correct digits") for method in methods]
).format(
    "{:.3e}", subset=[(method, "Estimated Pf") for method in methods + ["Exact"]]
).format(
    "{:.0f}", subset=[(method, "Nb Simu.") for method in methods]
)

### Note: 

- Problems with the number of simulations on the subset simulation algorithm (already noticed)
- The control works for Monte Carlo, we are getting pf=0 because we are limiting ourself to 10^5 simulations for 10^-7 pf (RP 28, 107, 111, 77)
- FORM, SORM, FORM-IS are KO in front of some functions and stop after 1 iteration

## Correct digits table

In [9]:
# Extract the Correct digits columns and modify style
df_correct_digits = df_multi.loc[:, (methods, "Correct digits")].copy()
df_correct_digits.columns = methods

In [10]:
latex_code = df_correct_digits.to_latex()
text_file = open("correct_digits.tex", "w")
text_file.write(latex_code)
text_file.close()

In [11]:
df_correct_digits_styled = (
    df_correct_digits.style.format("{:.2f}")
    .background_gradient(cmap="Blues", axis=1)
    .set_properties(**{"color": "black"})
)
df_correct_digits_styled

In [12]:
f = open("correct_digits_table.html", "w")
f.write(df_correct_digits_styled.render())  # df is the styled dataframe
f.close()

## Add in the html file to change the font
"""
html *
{
   font-family: "Computer Modern Sans", sans-serif;
}
"""

'\nhtml *\n{\n   font-family: "Computer Modern Sans", sans-serif;\n}\n'

Adaptation de la fonction background_gradient avec une échelle log

In [13]:
df = pd.DataFrame(
    [[66, 10000, 100, 10, 1], [666, 20000, 200, 20, 2], [6, 5000, 500, 50, 5]],
    columns=["a", "b", "c", "d", "e"],
)
df.style.background_gradient(cmap="Blues", axis=1)

In [14]:
def background_logscale_gradient(s, cmap="PuBu", low=0, high=0):
    rng = s.max() - s.min()
    # norm = colors.LogNorm(s.min() - (rng * low), s.max() + (rng * high))# Original
    norm = colors.LogNorm(s.min() + 1e-10, s.max())
    normed = norm(s.values)
    c = [colors.rgb2hex(x) for x in plt.cm.get_cmap(cmap)(normed)]
    return ["background-color: %s" % color for color in c]


test = df.style.apply(
    background_logscale_gradient, cmap="Blues", axis=1, subset=["b", "c", "d", "e"]
).set_properties(**{"color": "black"})
test

## Pf table

In [15]:
# Extract the Correct digits columns and modify style
df_pf = df_multi.loc[:, (["Exact"] + methods, "Estimated Pf")].copy()
df_pf.columns = ["Exact"] + methods

##df_pf.style.format("{:.3e}") # Version without background color modification
# df_pf.style.format("{:.3e}").background_gradient(cmap="Blues", axis=1) # unreadable with a linear scale
df_pf_styled = (
    df_pf.style.format("{:.3e}")
    .apply(background_logscale_gradient, cmap="Blues", axis=1)
    .set_properties(**{"color": "black"})
)
df_pf_styled

In [16]:
f = open("pf_table.html", "w")
f.write(df_pf_styled.render())  # df is the styled dataframe
f.close()

## Add in the html file to change the font

"""
html *
{
   font-family: "Computer Modern Sans", sans-serif;
}
"""

'\nhtml *\n{\n   font-family: "Computer Modern Sans", sans-serif;\n}\n'

## Run several algorithms on all problems and get detailed statistics

Run several algorithms on all reliability benchmark problems: print statistics on each problem.

In [17]:
def FormatRow(benchmarkResult):
    """Format a single row of the benchmark table"""
    result = [
        benchmarkResult.exactProbability,
        benchmarkResult.computedProbability,
        benchmarkResult.absoluteError,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
        benchmarkResult.numberOfDigitsPerEvaluation,
    ]
    return result

In [18]:
method_names = ["Monte-Carlo", "FORM", "SORM", "FORM-IS", "SUBSET"]

maximumOuterSampling = 10 ** 2
blockSize = 10 ** 2
coefficientOfVariation = 0.0

for i in tqdm(range(numberOfProblems)):
    problem = benchmarkProblemList[i]
    name = problem_names[i]
    exact_pf_name = "%10s" % ("Exact PF " + name[0:10])
    metrics = [
        exact_pf_name,
        "Estimated PF",
        "Absolute Error",
        "Correct Digits",
        "Function Calls",
        "Digits / Evaluation",
    ]
    results = np.zeros((len(method_names), len(metrics)))
    metaAlgorithm = otb.ReliabilityBenchmarkMetaAlgorithm(problem)
    # Monte-Carlo
    benchmarkResult = metaAlgorithm.runMonteCarlo(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[0, :] = FormatRow(benchmarkResult)
    # FORM
    benchmarkResult = metaAlgorithm.runFORM(nearestPointAlgorithm)
    results[1, :] = FormatRow(benchmarkResult)
    # SORM
    benchmarkResult = metaAlgorithm.runSORM(nearestPointAlgorithm)
    results[2, :] = FormatRow(benchmarkResult)
    # FORM-IS
    benchmarkResult = metaAlgorithm.runFORMImportanceSampling(
        nearestPointAlgorithm,
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[3, :] = FormatRow(benchmarkResult)
    # Subset
    benchmarkResult = metaAlgorithm.runSubsetSampling(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[4, :] = FormatRow(benchmarkResult)
    # Gather statistics and print them
    df = pd.DataFrame(results, index=method_names, columns=metrics,)
    # Format the columns for readability
    s = df.style.format(
        {
            exact_pf_name: lambda x: "{:.3e}".format(x),
            "Estimated PF": lambda x: "{:.3e}".format(x),
            "Absolute Error": lambda x: "{:.3e}".format(x),
            "Correct Digits": lambda x: "{:.1f}".format(abs(x)),
            "Function Calls": lambda x: "{:d}".format(int(x)),
            "Estimated PF": lambda x: "{:.2e}".format(x),
            "Digits / Evaluation": lambda x: "{:.1f}".format(abs(x)),
        }
    )
    display(s)

  0%|          | 0/26 [00:00<?, ?it/s]

  4%|▍         | 1/26 [00:02<01:03,  2.53s/it]

  8%|▊         | 2/26 [00:03<00:32,  1.34s/it]

 15%|█▌        | 4/26 [00:03<00:11,  1.84it/s]

 19%|█▉        | 5/26 [00:03<00:08,  2.43it/s]

 23%|██▎       | 6/26 [00:03<00:06,  3.03it/s]

 31%|███       | 8/26 [00:03<00:03,  4.59it/s]

 38%|███▊      | 10/26 [00:03<00:02,  5.42it/s]

 46%|████▌     | 12/26 [00:04<00:02,  6.96it/s]

 54%|█████▍    | 14/26 [00:04<00:01,  6.28it/s]

 62%|██████▏   | 16/26 [00:04<00:01,  7.70it/s]

 69%|██████▉   | 18/26 [00:05<00:01,  6.21it/s]

 73%|███████▎  | 19/26 [00:05<00:01,  6.50it/s]

 77%|███████▋  | 20/26 [00:08<00:04,  1.22it/s]

 81%|████████  | 21/26 [00:08<00:03,  1.49it/s]

 85%|████████▍ | 22/26 [00:09<00:03,  1.19it/s]

 88%|████████▊ | 23/26 [00:10<00:02,  1.49it/s]

 96%|█████████▌| 25/26 [00:10<00:00,  2.42it/s]

100%|██████████| 26/26 [00:10<00:00,  2.50it/s]